FROM ansibleplaybookbundle/apb-base:v3.11

RUN rm -f /etc/yum.repos.d/asb.repo && curl https://copr.fedorainfracloud.org/coprs/g/ansible-service-broker/ansible-service-broker-1.2.0-openshift-3.10/repo/epel-7/group_ansible-service-broker-ansible-service-broker-1.2.0-openshift-3.10-epel-7.repo -o /etc/yum.repos.d/asb.repo

LABEL "com.redhat.apb.spec"=\
"xxxxxx"

RUN yum -y downgrade apb-base-scripts && yum -y install automation-broker-apb-role && yum clean all

USER apb
