apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ansibleservicebrokers.osb.openshift.io
spec:
  group: osb.openshift.io
  names:
    kind: AnsibleServiceBroker
    listKind: AnsibleServiceBrokerList
    plural: ansibleservicebrokers
    singular: ansibleservicebroker
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
